-- MySQL Script generated by MySQL Workbench
-- Wed Mar  3 09:47:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Groupomania
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Groupomania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Groupomania` DEFAULT CHARACTER SET utf8 ;
USE `Groupomania` ;

-- -----------------------------------------------------
-- Table `Groupomania`.`Utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania`.`Utilisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Groupomania`.`Posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania`.`Posts` (
  `idPosts` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `Utilisateurs_id` INT NOT NULL,
  PRIMARY KEY (`idPosts`, `Utilisateurs_id`),
  INDEX `fk_Posts_Utilisateurs_idx` (`Utilisateurs_id` ASC),
  CONSTRAINT `fk_Posts_Utilisateurs`
    FOREIGN KEY (`Utilisateurs_id`)
    REFERENCES `Groupomania`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Groupomania`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Groupomania`.`Comments` (
  `idComments` INT NOT NULL AUTO_INCREMENT,
  `Posts_idPosts` INT NOT NULL,
  `Posts_Utilisateurs_id` INT NOT NULL,
  `Utilisateurs_id` INT NOT NULL,
  `contents` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idComments`, `Posts_idPosts`, `Posts_Utilisateurs_id`, `Utilisateurs_id`),
  INDEX `fk_Comments_Posts1_idx` (`Posts_idPosts` ASC, `Posts_Utilisateurs_id` ASC),
  INDEX `fk_Comments_Utilisateurs1_idx` (`Utilisateurs_id` ASC),
  CONSTRAINT `fk_Comments_Posts1`
    FOREIGN KEY (`Posts_idPosts` , `Posts_Utilisateurs_id`)
    REFERENCES `Groupomania`.`Posts` (`idPosts` , `Utilisateurs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_id`)
    REFERENCES `Groupomania`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
